### ISSUE TITLE
Find a drawing tool.

### ISSUE THREAD

**Issue by Crevil** [racketometer/thesis#3]
Find a tool that enables easy drawing of diagrams e.g. domain model.

Document the selection.

**Comment by Crevil** [comment]
I'm most fond of [StarUML](http://staruml.io/)
It's a lot like Visio, but with better alignment things and it is JSON source based, so it can be source controlled.
What do you say, @Karnich ? 

I considered not documenting the selection, as it seems kind of non-meaningful.

**Comment by Crevil** [comment]
I've been looking more into [LucidChart](https://www.lucidchart.com/). They got a pretty comprehensive library of drawings, not just UML as StarUML. That might be better. It got an education plan for free.

**Comment by Karnich** [comment]
Looks sweet lets go with that

**Comment by Crevil** [comment]
So be it. LucidChart is used.
